name: touchtact
description: An app to share and collect virtual business cards.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tailwind:
    path: tailwind
  tailwind_colors: ^0.3.1
  english_words: ^4.0.0
  provider: ^6.0.0
  font_awesome_flutter: ^8.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  tailwind_cli: ^0.5.4

flutter:
  uses-material-design: true